#!/usr/bin/env python3
"""SomaCampus Product Review and GUI Test Report - body PDF (ReportLab)."""
import hashlib
import os

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, HRFlowable, Image, KeepTogether, PageBreak, Paragraph,
    SimpleDocTemplate, Spacer, Table, TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

BASE = "/Users/jeffadhaya/Documents/Anti gravity Projects/School Management/SomaCampus"
SHOTS = os.path.join(BASE, "gui-test-screenshots")
OUT = os.path.join(BASE, "pdf_report", "body.pdf")

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG = colors.HexColor('#f3f2f1')
CARD_BG = colors.HexColor('#eae8e3')
TABLE_STRIPE = colors.HexColor('#f4f3f1')
BORDER = colors.HexColor('#d3d0c6')
ACCENT = colors.HexColor('#1f7693')
TEXT_PRIMARY = colors.HexColor('#1a1917')
TEXT_MUTED = colors.HexColor('#807e76')
SEM_SUCCESS = colors.HexColor('#3a8653')
SEM_ERROR = colors.HexColor('#9d463e')
SEM_WARNING = colors.HexColor('#a68a53')

# ── Fonts (macOS local TTFs) ──
SUPP = "/System/Library/Fonts/Supplemental"
pdfmetrics.registerFont(TTFont('Times New Roman', f'{SUPP}/Times New Roman.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman Bold', f'{SUPP}/Times New Roman Bold.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman Italic', f'{SUPP}/Times New Roman Italic.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman BoldItalic', f'{SUPP}/Times New Roman Bold Italic.ttf'))
pdfmetrics.registerFont(TTFont('Courier New', f'{SUPP}/Courier New.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman Bold',
                   italic='Times New Roman Italic', boldItalic='Times New Roman BoldItalic')
registerFontFamily('Courier New', normal='Courier New', bold='Courier New')

# ── Page geometry ──
PAGE_W, PAGE_H = A4
LM = RM = 0.9 * inch
TM = 0.95 * inch
BM = 0.9 * inch
AVAIL_W = PAGE_W - LM - RM  # ~465pt

# ── Styles ──
h1 = ParagraphStyle('H1', fontName='Times New Roman', fontSize=20, leading=26,
                    textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=4)
h2 = ParagraphStyle('H2', fontName='Times New Roman', fontSize=14, leading=19,
                    textColor=ACCENT, spaceBefore=14, spaceAfter=6)
body = ParagraphStyle('Body', fontName='Times New Roman', fontSize=10.5, leading=16,
                      textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8)
bullet = ParagraphStyle('Bullet', fontName='Times New Roman', fontSize=10.5, leading=15.5,
                        textColor=TEXT_PRIMARY, alignment=TA_LEFT, leftIndent=14,
                        spaceAfter=4)
caption = ParagraphStyle('Caption', fontName='Times New Roman Italic', fontSize=8.5,
                         leading=11.5, textColor=TEXT_MUTED, alignment=TA_CENTER,
                         spaceBefore=3, spaceAfter=6)
quote = ParagraphStyle('Quote', fontName='Times New Roman Italic', fontSize=10.5, leading=16,
                       textColor=TEXT_PRIMARY, leftIndent=24, spaceBefore=6, spaceAfter=8)
code_st = ParagraphStyle('Code', fontName='Courier New', fontSize=8.5, leading=12,
                         textColor=TEXT_PRIMARY, leftIndent=10, spaceAfter=2)
tbl_head = ParagraphStyle('TblHead', fontName='Times New Roman', fontSize=9.5, leading=12.5,
                          textColor=colors.white, alignment=TA_LEFT)
tbl_cell = ParagraphStyle('TblCell', fontName='Times New Roman', fontSize=9.5, leading=12.5,
                          textColor=TEXT_PRIMARY, alignment=TA_LEFT)
tbl_cell_c = ParagraphStyle('TblCellC', parent=tbl_cell, alignment=TA_CENTER)
stat_big = ParagraphStyle('StatBig', fontName='Times New Roman', fontSize=21, leading=25,
                          textColor=ACCENT, alignment=TA_CENTER)
stat_lbl = ParagraphStyle('StatLbl', fontName='Times New Roman', fontSize=8.5, leading=11,
                          textColor=TEXT_MUTED, alignment=TA_CENTER)
toc_h = ParagraphStyle('TOCTitle', fontName='Times New Roman', fontSize=20, leading=26,
                       textColor=TEXT_PRIMARY, spaceAfter=12)

story = []

# ── Helpers ──
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

AVAIL_H = PAGE_H - TM - BM
H1_ORPHAN = AVAIL_H * 0.15
MAX_KEEP = PAGE_H * 0.4

def safe_keep(elements):
    total = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total += h
    if total <= MAX_KEEP:
        return [KeepTogether(elements)]
    if len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def h1_rule():
    return HRFlowable(width='100%', thickness=1.2, color=ACCENT, spaceBefore=0, spaceAfter=10)

def section(num, title):
    story.append(CondPageBreak(180))
    story.extend(safe_keep([heading(f'{num}.  {title}', h1, 0), h1_rule()]))

def sub(title):
    story.append(CondPageBreak(140))
    story.append(heading(title, h2, 1))

def bind_headings(flowables):
    """Wrap each heading (or run of consecutive headings) with the first
    substantial flowable that follows it, so headings can never be orphaned
    at the bottom of a page."""
    out = []
    i = 0
    n = len(flowables)
    while i < n:
        el = flowables[i]
        if not hasattr(el, 'bookmark_name'):
            out.append(el)
            i += 1
            continue
        group = [el]
        j = i + 1
        # absorb consecutive headings
        while j < n and hasattr(flowables[j], 'bookmark_name'):
            group.append(flowables[j])
            j += 1
        # absorb spacing/page-break flowables up to the first substantial one
        while j < n and isinstance(flowables[j], (Spacer, CondPageBreak)):
            group.append(flowables[j])
            j += 1
        if j < n:
            group.append(flowables[j])
            j += 1
        total = 0
        for g in group:
            _, h = g.wrap(AVAIL_W, PAGE_H)
            total += h
        if total <= MAX_KEEP:
            out.append(KeepTogether(group))
        else:
            out.extend(group)
        i = j
    return out

def fig(fname, cap, max_h=250):
    path = os.path.join(SHOTS, fname)
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(AVAIL_W / ow, max_h / oh, 1.0)
    img = Image(path, width=ow * ratio, height=oh * ratio)
    img.hAlign = 'CENTER'
    story.extend(safe_keep([Spacer(1, 6), img, Paragraph(cap, caption)]))

def callout_stats(items):
    cells = []
    for big, lbl in items:
        inner = Table([[Paragraph(f'<b>{big}</b>', stat_big)], [Paragraph(lbl, stat_lbl)]],
                      colWidths=[AVAIL_W / len(items) - 12])
        inner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
            ('BOX', (0, 0), (-1, -1), 0.8, ACCENT),
            ('TOPPADDING', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, -1), (-1, -1), 9),
            ('TOPPADDING', (0, 1), (-1, 1), 1),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 1),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        cells.append(inner)
    row = Table([cells], colWidths=[AVAIL_W / len(items)] * len(items), hAlign='CENTER')
    row.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(Spacer(1, 6))
    story.append(row)
    story.append(Spacer(1, 10))

def data_table(headers, rows, ratios, zebra=True):
    widths = [r * AVAIL_W for r in ratios]
    data = [[Paragraph(f'<b>{x}</b>', tbl_head) for x in headers]]
    for r in rows:
        data.append([Paragraph(str(c), tbl_cell) if i != 0 else Paragraph(str(c), tbl_cell)
                     for i, c in enumerate(r)])
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    if zebra:
        for i in range(1, len(data)):
            style.append(('BACKGROUND', (0, i), (-1, i),
                          colors.white if i % 2 == 1 else TABLE_STRIPE))
    t.setStyle(TableStyle(style))
    return t

def add_table(headers, rows, ratios, cap=None):
    story.append(Spacer(1, 8))
    t = data_table(headers, rows, ratios)
    story.append(t)
    if cap:
        story.append(Spacer(1, 4))
        story.append(Paragraph(cap, caption))
    story.append(Spacer(1, 10))

def callout(text, color=ACCENT, bg=CARD_BG):
    inner = Table([[Paragraph(text, body)]], colWidths=[AVAIL_W - 8])
    inner.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), bg),
        ('LINEBEFORE', (0, 0), (0, -1), 3, color),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(Spacer(1, 4))
    story.append(inner)
    story.append(Spacer(1, 8))

# ── Header / footer ──
def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('Times New Roman', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LM, PAGE_H - 0.55 * inch,
                      'SomaCampus - Product Review and GUI Test Report')
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(LM, PAGE_H - 0.62 * inch, PAGE_W - RM, PAGE_H - 0.62 * inch)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LM, 0.62 * inch, PAGE_W - RM, 0.62 * inch)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LM, 0.45 * inch, 'Prepared by Z.ai - September 2026')
    canvas.drawRightString(PAGE_W - RM, 0.45 * inch, f'Page {doc.page}')
    canvas.restoreState()

doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=LM, rightMargin=RM, topMargin=TM, bottomMargin=BM,
    title='SomaCampus - Product Review and GUI Test Report',
    author='Z.ai', creator='Z.ai',
    subject='Code review and black-box GUI test of the SomaCampus School OS',
)

# ══════════ TOC page ══════════
story.append(Paragraph('<b>Table of Contents</b>', toc_h))
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC1', fontName='Times New Roman', fontSize=11.5, leading=18,
                   leftIndent=16, firstLineIndent=-16, textColor=TEXT_PRIMARY),
    ParagraphStyle('TOC2', fontName='Times New Roman', fontSize=10, leading=15,
                   leftIndent=34, firstLineIndent=-16, textColor=TEXT_MUTED),
]
story.append(toc)
story.append(PageBreak())

# ══════════ 1. Executive Summary ══════════
section('1', 'Executive Summary')
story.append(Paragraph(
    'SomaCampus is a school operating system for teachers and principals, built on React 19, '
    'Vite, Tailwind CSS and Supabase, and piloted at Grace\'s Cambridge Centre in Kampala. '
    'This review combines a full codebase audit with black-box GUI testing of the live '
    'application in a real browser, executed as the four everyday end users: teacher, '
    'principal, parent and student, using the seeded demo accounts.', body))
story.append(Paragraph(
    'The verdict is two-sided. The product looks and feels premium: the visual design system, '
    'role-aware navigation, and the daily-attendance workflow are genuinely better than most '
    'school software. The engineering culture is equally strong - the repository\'s own '
    'verification gate passes end to end, with database-contract audits, migration audits, '
    'TypeScript checks and 840 automated tests all green. But the product is not yet ready for '
    'its users: two of the six role homepages are broken in the live demo, the teacher\'s most '
    'important call-to-action dead-ends in an error, the principal\'s timetable publish flow is '
    'blocked by a missing database policy, and several dashboards present self-contradicting '
    'numbers that would erode a principal\'s trust within the first week.', body))
callout_stats([
    ('840 / 840', 'automated tests passing (verify:all gate)'),
    ('14', 'screens and flows GUI-tested in a live browser'),
    ('4', 'P0 broken journeys found in live testing'),
])
story.append(Paragraph(
    'All four blocking failures are integration- and data-contract issues rather than '
    'architectural ones, which is why they survived the automated gate: the unit and contract '
    'suites validate components and schema assumptions in isolation, while the broken journeys '
    'only manifest when a real Supabase session meets the seeded data. The recommended fix '
    'order in Section 8 is calibrated accordingly: restore the four dead ends, make the '
    'numbers agree, then run a product information-architecture pass for teachers.', body))

# ══════════ 2. Scope and Method ══════════
section('2', 'Scope and Method')
sub('2.1  Codebase review')
story.append(Paragraph(
    'The audit covered the application entry and routing (src/App.tsx), the authentication and '
    'role-resolution layer (src/lib/authContext.tsx, server-side role RPC with fail-closed '
    'behaviour), the design system (src/components/ui and layout), all 25 modules under '
    'src/modules, 71 Supabase migrations, and the verification tooling in .agents. The product '
    'spans six roles - teacher, principal, admin, bursar, parent and student - with modules for '
    'attendance, lesson delivery, assignments, timetable building with a constraint solver, '
    'HR and payroll, fees, expenses, inventory, communication and parent or student portals.', body))
sub('2.2  GUI test protocol')
story.append(Paragraph(
    'Black-box testing was executed in a real browser at 1440 by 900 against the development '
    'server and the live Supabase backend. Every conclusion is based on observed page behaviour, '
    'cross-validated between the accessibility tree and screenshots. Fourteen test points were '
    'executed across four personas; every screenshot referenced in this report is preserved in '
    'the gui-test-screenshots directory of the repository.', body))
callout('Environment preparation disclosure: the Vite dev server was started (port 5173) and '
        'seeded demo accounts were used exclusively. One write was performed during testing - '
        'marking one student absent in the Stage 5 Blue register - which is the flow under test '
        'and is audit-recorded by design. No code was modified during testing.', SEM_WARNING)
sub('2.3  Demo credentials used')
add_table(
    ['Persona', 'Account', 'Landing page'],
    [
        ['Teacher - Sarah Namukasa', 'teacher@somacampus.ug', '/teacher/today'],
        ['Principal - Dr. Edward Ssenyonga', 'principal@somacampus.ug', '/dashboard/school'],
        ['Parent - Florence Kyomugisha', 'parent@somacampus.ug', '/parent/home'],
        ['Student - Amari Kyomugisha', 'student@somacampus.ug', '/student/home'],
    ],
    [0.32, 0.38, 0.30],
    cap='Table 1 - Seeded demo accounts exercised during the test pass.')

# ══════════ 3. What works ══════════
section('3', 'What Works Well')
sub('3.1  Login and persona entry')
story.append(Paragraph(
    'The login screen sets the tone: clear brand identity, a descriptive card per role, and '
    'one-click sign-in for each verified demo persona. A teacher or principal needs no training '
    'to get in. This is a strong first impression and worth protecting.', body))
fig('t0_login.png', 'Figure 1 - Login screen with one-click verified demo personas.')
sub('3.2  Daily attendance register (the gold standard flow)')
story.append(Paragraph(
    'The class register is the best flow in the product. Tapping Present, Absent, Late or '
    'Excused updates live counters; editing an already-recorded day reveals an "Attendance Audit '
    'Mode" notice and an optional reason field; the save button shows an honest disabled '
    'spinner; and the dashboard card refreshes to the new tally (verified 9 present, 1 absent '
    'after save). Every register in the product should match this standard.', body))
fig('t4_absent_marked.png', 'Figure 2 - Register with audit mode, reason field and live counters.')
fig('t6_after_save.png', 'Figure 3 - Dashboard card updated after saving: 9 present, 1 absent.')
sub('3.3  Principal monitoring surfaces')
story.append(Paragraph(
    'The School Cockpit, Live Lessons Monitor and Fee Accounts render cleanly and load fast. '
    'The Live Lessons Monitor in particular does its one job well: expected versus submitted '
    'periods for the day, filters, and an expandable note per period. The data-accuracy issues '
    'affecting these screens are covered in Section 5; the interaction design itself is sound.', body))
fig('t10_live_lesson_detail.png', 'Figure 4 - Live Lessons Monitor with an expanded period note.')

# ══════════ 4. Critical failures ══════════
section('4', 'Critical Failures (P0)')
story.append(Paragraph(
    'Four journeys are broken end-to-end for ordinary users. Each is reproduced below with '
    'evidence and a code-level starting point.', body))

sub('4.1  F1 - Lesson Cockpit fails from the teacher\'s primary call-to-action')
story.append(Paragraph(
    'From the Teacher Today page, clicking "Open Scheduled Lesson" - the single most important '
    'teacher journey - lands on a URL of the form /teaching/classes/5555.../lessons/'
    'tt-entry-001 and renders "Lesson cockpit unavailable: Could not load lesson context for '
    'timetable entry tt-entry-001." The classroom cockpit is where lesson delivery, attendance '
    'and evidence capture live, so this dead-end blocks the core teaching loop.', body))
story.append(Paragraph(
    'Starting point: the identifier reaches src/modules/teaching/lessonService.ts (line 101, '
    'which raises "Could not load lesson context for timetable entry") but its context query '
    'fails against live data. The fixture-era identifier tt-entry-001 originates in '
    'src/modules/teacher/fixtures/teacherFixtures.ts; the live path should be verified to pass '
    'real timetable entry identifiers and to satisfy the cockpit\'s joins.', body))
fig('t2_lesson_cockpit_error.png', 'Figure 5 - Lesson Cockpit error after clicking the main CTA.')

sub('4.2  F2 - Parent portal cannot load the child overview')
story.append(Paragraph(
    'The Family Portal home (/parent/home) shows both a red error banner and an empty state at '
    'the same time - redundant double-failure messaging - and the failure persists across '
    'retries. For a parent, this screen is the whole product. Note that the page\'s fail-closed '
    'behaviour is correct and deliberate (src/modules/parent/ParentHomePage.tsx line 207); the '
    'defect is that the seeded demo data never satisfies the guardian resolution chain, so the '
    'flagship parent journey was never demonstrably green.', body))
story.append(Paragraph(
    'Starting point: the resolver walks auth user, then people.auth_user_id, then '
    'student_guardians, then active student_enrolments (src/modules/auth/parentIdentity.ts). '
    'Verify that the parent@somacampus.ug auth user is linked to a person row with a '
    'student_guardians row for Amari Kyomugisha, and that RLS grants the select.', body))
fig('t12_parent_home.png', 'Figure 6 - Parent portal: error banner plus empty state shown together.')

sub('4.3  F3 - Student portal leaks a raw database error to a child')
story.append(Paragraph(
    'The student home (/student/home) renders the literal database engine error "JSON object '
    'requested, multiple (or no) rows returned" in a red banner. Showing a PostgREST PGRST116 '
    'message to a primary-school student is the exact class of leak the repository\'s own '
    'Production Trust Gate forbids.', body))
story.append(Paragraph(
    'Starting point: src/modules/online/StudentOnlineHomePage.tsx (line 71) assigns '
    'err.message directly to the visible load error. The service call beneath it performs a '
    'single-row lookup that returns zero or multiple rows for the demo student. Map engine '
    'errors to friendly copy, log the detail to the console, and fix the underlying lookup.', body))
fig('t13_student_home.png', 'Figure 7 - Student home showing the raw PostgREST error string.')

sub('4.4  F4 - Timetable publishing is blocked by a missing database policy')
story.append(Paragraph(
    'The principal\'s Timetable Wizard completes all four guided steps - foundation check, '
    'staffing auto-fill, schedule generation, and week-grid review - but clicking '
    '"Publish timetable" fails with "new row violates row-level security policy for table '
    'timetables." The entire planning journey therefore dead-ends at its final step. This '
    'finding was independently reproduced by a second end-to-end test pass of the wizard and '
    'verified against the migration history during this review.', body))
story.append(Paragraph(
    'Root cause, verified: the timetables and timetable_entries tables have exactly one policy '
    'each - timetables_auth_read and timetable_entries_auth_read, both FOR SELECT only '
    '(supabase/migrations/20260903000000_somacampus_core_schema.sql lines 368-369). No later '
    'migration adds INSERT or UPDATE policies for either table. The wizard\'s publish handler '
    '(src/modules/planning/TimetableWizard.tsx, publishAll, line 272) performs a direct insert '
    'into timetables and then into timetable_entries, which PostgreSQL fail-closes.', body))
story.append(Paragraph(
    'A corroborating signal from this review\'s own test session: the Master Timetable page '
    'displays "Status: PUBLISHED" with 15 periods scheduled, yet the UI publish path is '
    'impossible - so the published state can only have arrived through seed data or '
    'service-role writes, never through the product itself.', body))
callout('Recommended fix - use the atomic RPC, not broader policies. The codebase already '
        'contains approve_timetable_atomic and publish_timetable_atomic as SECURITY DEFINER '
        'functions with in-function leadership checks (migration 20260916000000). The wizard '
        'bypasses its own architecture by inserting directly and only then calling the RPCs. '
        'Moving timetable and entry creation into an atomic RPC keeps RLS fail-closed, closes '
        'the orphaned-timetable window between the two direct inserts, and avoids maintaining '
        'leadership gating in two places. Adding direct INSERT/UPDATE policies would also '
        'unblock the button but is the weaker option.', SEM_ERROR)

# ══════════ 5. Data trust defects ══════════
section('5', 'Data-Trust Defects (P1)')
story.append(Paragraph(
    'These screens render, but the numbers contradict each other. For school staff, a number '
    'they cannot trust is worse than no number at all. Each item below was observed in a single '
    'session on the live demo data.', body))
add_table(
    ['#', 'Where', 'Defect observed', 'Anchor'],
    [
        ['D1', 'Principal cockpit KPI row vs its own chart',
         'Student Attendance reads 0% with a "-90.0% this week" delta while the adjacent '
         'chart shows bars near 90-100; Active Teaching Staff reads "6, 0% staff present". '
         'A negative percentage delta is also nonsensical formatting.',
         'SchoolDashboardPage'],
        ['D2', 'Teacher Today date',
         'Header shows "Tuesday, 3 September 2026" on Friday 11 September 2026. The label is '
         'hardcoded in the live code path, together with hardcoded school events.',
         'teacherService.ts:370'],
        ['D3', 'Teacher Today timetable',
         '"MY TEACHING TIMETABLE" lists lessons taught by other teachers (David Musoke, James '
         'Kato) and says "24 enrolled" while the class card on the same page says 10 students.',
         'teacherService.ts / fixtures'],
        ['D4', 'Attendance card vs register modal',
         'Before the test edit, the class card reported 7 present / 1 absent while the register '
         'modal reported 10 present / 0 absent - two different truths one click apart.',
         'attendance service'],
        ['D5', 'Fee Accounts ledger',
         'A student with UGX 0 assessed, UGX 0 paid and UGX 0 balance is flagged "Overdue". '
         'No-data is being treated as arrears.',
         'fees clearance logic'],
        ['D6', 'Assignments list',
         'Records named TEST_Audit_Score_Assignment, TEST_Principal_Override_Assignment and '
         'TEST_Math_Fractions_HW are visible to teachers in the live list.',
         'demo data hygiene'],
        ['D7', 'Time formats',
         'Three formats on one page: "12:43 AM" (fixture stamp), "08:07 PM" (real save) and '
         '24-hour "07:55" (clock-in).',
         'display layer'],
    ],
    [0.06, 0.20, 0.56, 0.18],
    cap='Table 2 - Observed data-trust defects with code or data anchors.')
fig('t9_principal_cockpit.png', 'Figure 8 - Principal cockpit: KPI row contradicts the chart below it.',
    max_h=280)
fig('t11_fees.png', 'Figure 9 - Fee ledger: zero-balance account flagged Overdue.')

# ══════════ 6. Product review ══════════
section('6', 'Product and UX Review (Teacher and Principal Lens)')
sub('6.1  Strengths worth protecting')
for b in [
    'Visual design is top-notch. The dark-teal navigation rail, light workspace, Plus Jakarta '
    'Sans typography and a consistent card and status-pill system read premium in every '
    'screenshot; nothing looked misaligned or cheap.',
    'Information architecture matches the school day. Teachers land on Today with clock-in, '
    'class responsibilities, the current lesson and events; principals get a cockpit, live '
    'lessons and finance. Role-based navigation filtering works - teachers never see payroll.',
    'The attendance register is the UX gold standard for the whole product (Section 3.2), and '
    'the four-step Timetable Wizard with auto-fill, week grid, bell bands and in-grid slot '
    'editing is a major step forward for principals - once the publish blocker (F4) is fixed.',
    'An honest engineering culture is real: fail-closed services, server-side privacy gating, '
    'archive-not-delete, honest placeholders for unbuilt features, and an 840-test gate.',
]:
    story.append(Paragraph(f'•  {b}', bullet))
sub('6.2  Concerns for the target users')
for b in [
    'Teachers are shown engineering, not their job. The teacher\'s Master Timetable page opens '
    'with "Teaching Allocation Architecture ... Deterministic CSP Solver", allocation approval '
    'steps and a "Run Constraint Solver" button. Allocation and solving are principal or admin '
    'work; a teacher needs "my week, my classes, my room changes". A read-only personal week '
    'grid would serve teachers far better. The same double-header problem affects principals in '
    'the wizard itself, where the legacy three-step summary cards and the wizard\'s own '
    'breadcrumb stack two navigation systems on one screen - a finding made independently by '
    'both test passes in this review.',
    'Navigation breadth: roughly 18 destinations for a teacher, with Worksheets and Quizzes as '
    'placeholders in the primary group. Consider demoting unbuilt items.',
    'Dev scaffolding leaks into user space: the green "Role: teacher" chip in the header is a '
    'development persona switcher, and the "Academic Year 2026-2027 - Cambridge Primary" '
    'context chip is hardcoded and will rot.',
    'Accessibility gaps: the 40 register status toggles are unnamed buttons in the accessibility '
    'tree (statuses are not associated with student names), the register close button has no '
    'accessible name, and the selected "Absent" chip is dark red on dark red with poor contrast.',
    'Login cards promise more than the product delivers: "Diagnostic quizzes and learning '
    'profile" leads to an empty shell for the student persona. Set expectations or build a '
    'minimal real version.',
]:
    story.append(Paragraph(f'•  {b}', bullet))
fig('t1_teacher_today.png', 'Figure 10 - Teacher Today: strong layout, but stale date and mixed '
    'instructor names on "MY TEACHING TIMETABLE".', max_h=260)
fig('t8_master_timetable.png', 'Figure 11 - Master Timetable: solver jargon presented to teachers.')

# ══════════ 7. Code health ══════════
section('7', 'Code Health')
sub('7.1  Verification gate')
callout('npm run verify:all - PASS. Database-contract audit, migration audit, TypeScript '
        'checks, and the Vitest suite: 94 test files, 840 tests passed, 26 skipped (live-database '
        'tests). Mock-rot, contract and migration scanners all report clean.', SEM_SUCCESS)
sub('7.2  Findings')
for b in [
    'Fixture-live boundary is blurred: INITIAL_TEACHER_SCHEDULE in '
    'src/modules/teacher/fixtures/teacherFixtures.ts backs the mock path, and fixture-era '
    'identifiers such as tt-entry-001 exist in the live database - the direct source of F1.',
    'Error surfacing pattern: several pages assign err.message directly to visible error '
    'banners; the student portal proves the risk. Standardise on friendly copy plus logged '
    'detail.',
    'Oversized files (maintainability): InventoryPage.tsx (2,113 lines), types/domain.ts '
    '(1,685), TimetableDraftPage.tsx (1,616), StudentDetailPage.tsx (1,473), and nine further '
    'files above 800 lines.',
    'No route-level code splitting: the entire app is one eager bundle (about 81k lines of '
    'TypeScript), which teachers on tablets or constrained networks will feel on first load.',
    'Persona names in the development switcher (for example "Dr. Florence Namugga") do not '
    'match the seeded users ("Dr. Edward Ssenyonga") - a small but confusing demo detail.',
    'Zero TODO or FIXME markers - unusually clean; incompleteness is tracked honestly through '
    'placeholder modules and phase documents instead.',
]:
    story.append(Paragraph(f'•  {b}', bullet))

# ══════════ 8. Roadmap ══════════
section('8', 'Recommended Fix Order')
add_table(
    ['Priority', 'Work item', 'Why first'],
    [
        ['P0', 'Restore the four dead ends: Lesson Cockpit context for live timetable entries; '
               'parent-to-child seed linkage (student_guardians plus auth_user_id for the demo '
               'parent); map PGRST116 on the student home to friendly copy; and route timetable '
               'publish through an atomic create-and-fill RPC so RLS stays fail-closed '
               '(Section 4.4).',
         'These are the journeys teachers, parents and principals take first.'],
        ['P1', 'Make the numbers agree: cockpit attendance and staff KPIs versus chart, '
               'enrolment counts (10 versus 24), attendance card versus register, fees '
               '"Overdue" on zero accounts, real date in teacherService.ts line 370.',
         'One contradiction costs more trust than one missing feature.'],
        ['P1', 'Purge TEST_* rows from the demo database and add a seed-validation rule '
               'against the TEST_ prefix.',
         'Test pollution in a teacher\'s live list reads as unprofessional.'],
        ['P2', 'Product IA pass for teachers and principals: collapse the legacy solver header '
               'when the guided wizard is active (confirmed independently by two test passes), '
               'give teachers a personal week view, move solver and allocation controls behind '
               'principal or admin, demote placeholder nav items.',
         'Sharpens the product for its primary daily users.'],
        ['P2', 'Accessibility sweep (button naming, chip contrast) and one timestamp format '
               'everywhere.',
         'Removes friction for assistive-tech users and standardises reading.'],
    ],
    [0.10, 0.62, 0.28],
    cap='Table 3 - Remediation roadmap in recommended order.')
story.append(Paragraph(
    'The dev server used for testing was left running at http://localhost:5173, and all '
    'fourteen screenshots are preserved under gui-test-screenshots in the repository. No '
    'production code was changed during this review.', body))

# ══════════ Appendix ══════════
story.append(PageBreak())
section('Appendix A', 'GUI Test Point Matrix')
add_table(
    ['#', 'Test point', 'Result', 'Evidence'],
    [
        ['T0', 'Login page and one-click personas', 'PASS', 't0_login.png'],
        ['T1', 'Teacher Today dashboard loads', 'PASS (data issues, see D2/D3)', 't1_teacher_today.png'],
        ['T2', 'Lesson Cockpit from "Open Scheduled Lesson"', 'FAIL', 't2_lesson_cockpit_error.png'],
        ['T3', 'Attendance register modal opens', 'PASS (mismatch vs card, D4)', 't3_attendance_register.png'],
        ['T4', 'Mark student absent, audit mode appears', 'PASS', 't4_absent_marked.png'],
        ['T5', 'Save attendance with reason', 'PASS', 't5_attendance_saved.png'],
        ['T6', 'Dashboard card refreshes after save', 'PASS', 't6_after_save.png'],
        ['T7', 'Assignments list and filter tabs', 'PASS (TEST_ rows, D6)', 't7_assignments.png'],
        ['T8', 'Master Timetable week grid renders', 'PASS', 't8_master_timetable.png'],
        ['T9', 'Principal School Cockpit', 'PASS (KPI contradictions, D1)', 't9_principal_cockpit.png'],
        ['T10', 'Live Lessons Monitor and period detail', 'PASS', 't10_live_lesson_detail.png'],
        ['T11', 'Fee Accounts ledger', 'PASS (Overdue logic, D5)', 't11_fees.png'],
        ['T12', 'Parent Home and Overview', 'FAIL (persistent)', 't12_parent_home.png'],
        ['T13', 'Student Online Home', 'FAIL (raw DB error)', 't13_student_home.png'],
        ['T14', 'Timetable Wizard four-step walkthrough and publish', 'FAIL at publish (RLS, F4)', 'code-verified'],
    ],
    [0.07, 0.42, 0.26, 0.25],
    cap='Table 4 - Fourteen GUI test points across four personas, plus the code-verified wizard '
        'publish pass (F4). Screenshots in gui-test-screenshots.')

story.append(PageBreak())
section('Appendix B', 'Screenshot Index')
add_table(
    ['File', 'Moment captured'],
    [
        ['t0_login.png', 'Login screen with persona cards'],
        ['t1_teacher_today.png', 'Teacher Today dashboard (full page)'],
        ['t2_lesson_cockpit_error.png', 'Lesson Cockpit unavailable error'],
        ['t3_attendance_register.png', 'Register modal, initial state'],
        ['t4_absent_marked.png', 'Absent marked, audit mode and reason field'],
        ['t5_attendance_saved.png', 'Save in progress with spinner'],
        ['t6_after_save.png', 'Dashboard card updated after save'],
        ['t7_assignments.png', 'Assignments list with TEST_ rows'],
        ['t8_master_timetable.png', 'Master Timetable and solver controls'],
        ['t9_principal_cockpit.png', 'Principal cockpit (full page)'],
        ['t10_live_lesson_detail.png', 'Live Lessons Monitor, period expanded'],
        ['t11_fees.png', 'Fee Accounts ledger with Overdue flag'],
        ['t12_parent_home.png', 'Parent portal failure state'],
        ['t13_student_home.png', 'Student portal raw database error'],
    ],
    [0.30, 0.70],
    cap='Table 5 - Evidence index. All files are in gui-test-screenshots/ at the repository root.')

doc.multiBuild(bind_headings(story), onFirstPage=on_page, onLaterPages=on_page)
print('body.pdf built OK')
